server:
    port: 8081
spring:
    thymeleaf:
        prefix: file:src/main/resources/templates/
    jpa:
        #database-platform: org.hibernate.dialect.PostgreSQLDialect
        database-platform: org.hibernate.dialect.MySQLDialect
        open-in-view: false
        hibernate:
            ddl-auto: none
    datasource:
        driver-class-name: org.postgresql.Driver
        #driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:postgresql://ec2-52-7-228-45.compute-1.amazonaws.com/d1e3e8ln4j4kfn
        #url: jdbc:mysql://localhost:3306/miempresa
        username: lybyhyxfnddoke
        password: fd55af35efa837dbed4e0f90fc0b62eabc5805dc459f78574e4e95e3c59b75bc